/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QualMaiorDosDois;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
        
        
       

        int num1 = 0;
        int num2 = 0;
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite o primeiro numero: ");
        num1 = leitor.nextInt();
        
        System.out.println("Digite o segundo numero: ");
        num2 = leitor.nextInt();
        
        if(num1 > num2){
            System.out.println("Primeiro numero e maior que segundo.");
        }else{
               System.out.println("Segundo numero e maior que o primeiro.");
        }
        
        
    }
}
